let pixel_array = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
radio.setGroup(1)
pixel_array.showColor(neopixel.colors(NeoPixelColors.Red))
kitronik_servo_lite.forward()
basic.pause(5000)
pixel_array.showColor(neopixel.colors(NeoPixelColors.Blue))
kitronik_servo_lite.turnRight(180)
pixel_array.showColor(neopixel.colors(NeoPixelColors.Green))
kitronik_servo_lite.forward()
basic.pause(5000)
pixel_array.showColor(neopixel.colors(NeoPixelColors.Purple))
kitronik_servo_lite.turnLeft(180)
pixel_array.showColor(neopixel.colors(NeoPixelColors.White))
kitronik_servo_lite.backward()
basic.pause(5000)
